### ISSUE TITLE
bz2 archive format support

### ISSUE THREAD

**Issue by peter279k** [matomo-org/component-decompress#15]
As title, it seems that this package misses the `.tar.bz2` archive decompress support.

If possible, considering this issue and add this feature to resolve issue.

Once this issue is accepted, I can work on this. And also suggest recommendations to tell me how to resolve this issue :).

**Comment by peter279k** [comment]
@tsteur, do you have any idea about this?

**Comment by tsteur** [comment]
@peter279k If you need support for bz2 feel free to create a PR and we would review and merge. From our side we currently don't need it AFAIK and wouldn't know how to add support for bz2.

**Comment by peter279k** [comment]
Closed via PR #16.
